### ISSUE TITLE
parse error when exist escape characters

### ISSUE THREAD

**Issue by lost22git** [LilyRose2798/jasper#1]
# code

```gleam
pub fn jasper_test() {
  let json_str = "
{
  \"data\": \"{\\\"foo\\\": [{\\\"name\\\": \\\"x\\\"},{\\\"name\\\": \\\"y\\\"}]}\", 
}
" 

 let assert Ok(json) = parse_json(json_str)
 let assert Ok(String(str)) = query_json(json, Root |> Key("data"))

  io.debug("parse result: " <> str)
}
```

# error info

```
 #{function => <<"jasper_test">>,line => 18,
       message => <<"Assertion pattern match failed">>,
       module => <<"lib_jasper">>,
       value => {error,{unexpected_token,<<"{">>}},
       gleam_error => let_assert}

```

**Comment by LilyRose2798** [comment]
Thanks for the bug report! I've located and fixed this parsing issue in v1.2.2 (e4ce45c8).
The issue was that the escape code parser was never ran due to the string parser not excluding backslashes as it should have been, so changing the code from `none_of(["\""]) |> alt(escape)` to `none_of(["\"", "\\"]) |> alt(escape)` fixed the issue.
Just so you're aware, the JSON you included above is still not valid, but that is due to the trailing comma at the end of the string (which aren't allowed as part of the JSON spec). Removing the comma allows the above JSON to parse successfully in the latest version.
